ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:checkedbox: pass:normal[{startsb}&#10004;{endsb}]

= Pivotal Spring Cloud Workshop

== Overview

[.lead]
This workshop provides developers with hands-on experience building cloud native applications with microservice architectures using Spring Cloud.  Included are presentations and hands-on labs.

== Sessions

IMPORTANT: Each new lab exercise builds upon the preceding lab, so if you skip around the labs do so at your own risk!

* Session 1: link:presentations/Session_1_Intro_SC.pdf[_Introducing Spring Cloud Netflix_]
* Session 2: link:presentations/Session_2_SC_Config.pdf[_Spring Cloud Config_]
** Lab 1: link:labs/lab01/lab01.adoc[Introducing Spring Cloud into a Boot Application]
* Session 3: link:presentations/Session_3_SC_Discovery_LB.pdf[_Spring Cloud Netflix - Service Discovery & Load Balancing_]
** Lab 2: link:labs/lab02/lab02.adoc[Microservice Service Discovery and Load Balancing]
* Session 4: link:presentations/Session_4_Circuit_Breaker.pdf[_Spring Cloud Netflix - Circuit Breakers_]
** Lab 3: link:labs/lab03/lab03.adoc[Microservice Fault Tolerance with Circuit Breakers]

== Lab Setup

To build the applications in this workshop, you'll need a couple of things:

* https://help.github.com/articles/set-up-git/#setting-up-git[Git]
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java JDK 8]
* Your favorite IDE or editor (e.g., http://www.eclipse.org[Eclipse] or https://spring.io/tools[Spring Tool Suite], https://www.jetbrains.com/idea[IntelliJ IDEA], https://netbeans.org[NetBeans], Visual Studio, etc)

We'll be pushing applications and creating services in Pivotal Cloud Foundry (PCF). If you don't have an account on a Pivotal Cloud Foundry (PCF) instance then use Pivotal Web Services, an instance of PCF hosted by Pivotal.

* Login or signup for a free http://run.pivotal.io[Pivotal Web Services] account
* Click the _Tools_ link and...
** download and install the CLI matching your operating system
** login to the CF CLI (`cf login -a api.run.pivotal.io`)

== Spring Cloud Services and Self-Signed SSL Certificates
As mentioned in the PCF https://docs.pivotal.io/spring-cloud-services/1-5/common/service-registry/writing-client-applications.html[Spring Cloud Services online documentation]. Spring Cloud Services uses HTTPS for all client-to-service communication. If your PCF installation is using a self-signed SSL certificate, the certificate will need to be added to the JVM truststore.

Spring Cloud Services can add the certificate for you automatically. For this to work, you must set the TRUST_CERTS environment variable on your application to the API endpoint of your Elastic Runtime instance. You can do this at the CF CLI or add it to a manifest file of your application.

To do this in the CLI, execute the following command where target.cf.com should be changed with your target.

[source,log]
----
$ cf set-env my-app TRUST_CERTS target.cf.com
Setting env variable 'TRUST_CERTS' to 'target.cf.com' for app my-app in org myorg / space development as user...
OK
TIP: Use 'cf restage my-app' to ensure your env variable changes take effect
$ cf restage my-app
----

Alternatively, you can add it to a manifest file where target.cf.com should be changed with your target. 

[source,bash]
----
---
  ...
  env:
    TRUST_CERTS: target.cf.com
----

== Java 9 
IMPORTANT: As of February 2018
JDK 9 has deprecated the java.xml.bind module which is to be removed, see: https://docs.oracle.com/javase/9/docs/api/java.xml.bind-summary.html. If you get a Class Not Found exception for JAXB `java.lang.ClassNotFoundException: javax.xml.bind.JAXBException` then in the Maven pom.xml add:

[source,xml]
----
<dependency>
  <groupId>javax.xml.bind</groupId>
  <artifactId>jaxb-api</artifactId>
  <version>2.3.0</version>
</dependency> 
----

== Clone repo

To follow along with the lab exercises, please clone this git repo on your local machine

[source,bash]
----
$ git clone https://github.com/cdevpivotal/sc-workshop.git
----

== IDE Setup and tips

TIP: This section shares some optional tips for configuring your IDE for an optimal experience during the workshop!

=== Eclipse / Spring Tool Suite

Exclude `java.awt.*` from auto-complete suggestions::
`Preferences -> Java -> Appearance -> Type Filters -> Add... -> java.awt.*`
+
This way when you need to auto import something with `List` you don’t get the dialog box that asks if you want `java.awt.List` when you really want `java.util.List`

Configure Maven Auto Update::
`Preferences -> Maven -> {checkedbox} Automatically update Maven projects configuration`
+
Allows you to change a `pom.xml` and have the eclipse classpath automatically change without having to trigger the change manually.

Open pom.xml in XML view::
`Preferences -> Maven -> User Interface -> {checkedbox} Open XML Page in the POM editor by default`
+
This will get you straight to the XML when you first open your `pom.xml`

Show line numbers::
`Preferences -> General -> Editors -> Text Editors -> Show Line Numbers`
+
Very useful when collaborating and you need to explicitly state which line number you are referring to.

Automatically refresh resources changed outside of Eclipse::
`Preferences -> General -> Workspace -> Refresh using native hooks or profiling`
+
This enables Eclipse to recognize changes to files that have been modified outside of Eclipse. Pretty handy.


Close all views you don’t need::
Give yourself more space to view/write code by closing any views in the perspective that you don’t use, such as: Outline, Spring Explorer, and Servers

Boot Dashboard::
Use it, it’s awesome :)
